### PR TITLE
[LIMS] - Added mockup for create_session, still used by Qt mockup code

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
The method `create_session` is used by the qt mockup code

### CODE REVIEW

**Review by rhfogh — CHANGES_REQUESTED** [review]
The store_robot_action fix worked - so we now find the next bug:

Traceback (most recent call last):
  File "/home/rhfogh/pycharm/mxcubecore/mxcubecore/queue_entry/base_queue_entry.py", line 432, in execute
    gid = HWR.beamline.lims._store_data_collection_group(group_data)
  File "/home/rhfogh/pycharm/mxcubecore/mxcubecore/HardwareObjects/abstract/ISPyBAbstractLims.py", line 214, in _store_data_collection_group
    return self.adapter._store_data_collection_group(group_data)
  File "/home/rhfogh/pycharm/mxcubecore/mxcubecore/BaseHardwareObjects.py", line 1060, in __getattr__
    raise AttributeError(attr)
AttributeError: adapter

**Comment by marcus-oscarsson** [comment]
Thanks, `_store_data_collection_group` was indeed also missing. The leading _ is a bit misleading but I guess we can make this `store_data_collection_group` part of the public interface (its not at the moment). I hope there are no more missing functions in `ISPyBClientMockup` now.

**Review by rhfogh — APPROVED** [review]
Now it works in mock on my laptop

**Comment by marcus-oscarsson** [comment]
Ill merge this then, can I let you take care of bumping the `mxcubecore` version used in mxcubeqt ?

**Pull request merged**
