### PR TITLE
Improve errors

### PR DESCRIPTION
**Pull request by drboer**

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hi @drboer 

Sorry for taking some time to have a look at this, its been awfully busy the last period. I generally have the same remarks as @beteva. There are some conflicts that would be important to have a look at and a few things committed that does not seem to be intended to actually be committed :). 

We have a PR #686 that will soon be finished so that will change some queue imports that might require some alterations to the code in this PR. However I'm happy to do it if its already merged (its not really a big change). So it would be good to know if you will have the time to have a look at this the coming week so that we can proceed and merge #686. Otherwise we will just need to mange those changes afterwards which will work fine as well, but I at-least wanted to let you know about where we are :).

**Comment by drboer** [comment]
> Hi @drboer, unfortunately, as you can see, there are conflicts and your code cannot be merged. Also, it is quite difficult to merge such a big PR (133 files and 80 commits). In order to make it easier to merge, could you, please, split your PR in two parts - the ALBA specific and the generic files. Would it be also possible, that you remove your test comments, so some of the files will remain unchanged (like Hardwarerepository.py) Thank you

Hi Antonia and Marcus, 
Sorry guys, I am new to this. I replied by mail but now see that my reply is not included here. Thanks for the messages.

The merge request was an error, please disregard. I should have notified you that it was not meant to be sent to the mxcube repository. I intended to merge branches in my repository, not with the mxcube master branch.

I am working on a merge between the xaloc production branch and the mxcube master branch, but both are changing quite rapidly and I have not been able to finish this yet. The inclusion of pydantic in mxcube triggered the need for an update of the environment in which we run mxcube at XALOC. This triggered me to upgrade python to version 3.9 and Qt to version 5, without realizing how much work that is. This is in progress..

Apologies again for the time lost,

Best wishes,

Roeland

Best,

Roeland.

**Comment by rhfogh** [comment]
Hi @drboer It is great to hear that you are working to upgrade your local branch to develop - even though that is a big job with everything changing so fast. I look forward to the result. From my side, I am working on pretty much rebuilding much of the GPhL code to fit in the develop branch, and adapt to the changes I made there to fit MASSIF-1 automation. It is indeed hard to merge things with changes happening fast on both sides.

If there are conflicts on GPhL-only files, please just keep what is already in develop. I shall port over all necessary changes as part of the rewrite.

**Comment by marcus-oscarsson** [comment]
Hi @drboer,

No problem at all. It is indeed strange that email got lost somewhere. We are very happy to see that you have made, even if the work is not completely done, lots of progress. If you at some point need some assistance with the merge lets us know and we will see what we can do :)

I will close this PR in the mean time.

**Pull request closed without merging**
