### PR TITLE
Define set_value for better precision.

### PR DESCRIPTION
**Pull request by beteva**
The precision depends on the difference between the current resolution and the target value - the smaller the difference, he better the precision.
Move twice to get the closet possible to the requested resolution

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
Looks fine

**Comment by beteva** [comment]
Hi @all, can we merge this?

**Comment by rhfogh** [comment]
This still shows "Some checks haven’t completed yet". Should we ignore this? Or is there some problem in the  testing tha needs fixing?

**Comment by marcus-oscarsson** [comment]
I think we should look over our CI and maybe change from travis to something else, its been relay slow lately. I even think they have changed something in their infrastructure so might need to update it to make it work properly. Its alright for the moment that we merge without this being run but we need to take a closer look at the CI in the near future.

**Pull request merged**
