### PR TITLE
[type hint] fix for Python 3.8 incompatible typehints

### PR DESCRIPTION
**Pull request by jbflo**
@marcus-oscarsson  @woutdenolf As suggest i had the the line to fix the [issue](https://github.com/mxcube/mxcubecore/issues/1030)

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
I do not know why this fixes the issue. I must say I never understood how `from __future__ import annotations` works.

If it were me, I think I would have actually fixed the type annotations ( `typing.Dict[str]` I guess). But I am fine with this fix if it means we do not have to change it back again to `dict[str]` later when we get rid of Python 3.8.

**Comment by fabcor-maxiv** [comment]
But bigger issue, I do not know why this issue went undetected by our checks... that is not good.

**Comment by jbflo** [comment]
> But bigger issue, I do not know why this issue went undetected by our checks... that is not good.

Yeah.. In addition of this easy fix, we could maybe investigate why it passed the check .

**Comment by marcus-oscarsson** [comment]
Hm, its more two separate issues I would say. I also prefer to explicitly do `from typing import Dict` but `from __future__ import annotations` would also work especially as we would remove it once we drop support for `Python 3.8` (which I guess could be relatively soon)

Yes, we should investigate why the tests passed even though they should not have. The application should not even have started with Python 3.8, so it is indeed strange.

**Review by fabcor-maxiv — APPROVED** [review]

**Pull request merged**
