### PR TITLE
Deprecating Device and Equipment

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
The `Device` and `Equipment` classes are still in the code base but now with a deprecation warning. There are still a few more objects that use Device and Equipment to look at. Please have a look at your site specific and local code, let me know and make the necessary changes. I will follow up with a PR that removes `Equipment` and `Device`

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
I do not know much about making deprecations.

This page says we should put one in `__init_subclass__`: https://dev.to/hckjck/python-deprecation-2mof

**Comment by marcus-oscarsson** [comment]
I guess its in-case the subclass does not call `__init__`

**Review by rhfogh — APPROVED** [review]
Looks good. The warnings will not have the same effect as an exception, right?

**Comment by beteva** [comment]
> The warnings will not have the same effect as an exception, right?

The warning only prints the text. It does not raise any exception and does not stop the execution.

**Pull request merged**
