### PR TITLE
First draft for MEP-01

### PR DESCRIPTION
**Pull request by jordiandreu**
This is the first draft for the `mxcubecore` enhancement proposal. This proposal is related to the versioning and release models.
I have following the guidelines (also under discussion) under #614. You can access the document [here](https://github.com/jordiandreu/HardwareRepository/blob/MEP01_versioning_and_releases/doc/MEPS/MEP-01/mep01.md).

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Thanks, looks good ! I guess there might be some details to discuss but the general procedure is in my opinion clearly expressed.

**Comment by marcus-oscarsson** [comment]
See discussion #618

**Comment by jordiandreu** [comment]
As I did proposed in the last developers meeting, I have implemented the gitflow model as described in the MEP-01 using the bumpversion tool in a demo repository: https://github.com/jordiandreu/test_action
In addition, I have also configured some github actions to automate the commit and version bumping in most cases.

You will find a step-by-step guide about how to work with the different branches with this bumpversion and github actions configuration in the README file.

As I mentioned before, this implements the git flow model (master/release/develop + feature branches + hot fixes). Nevertheless, while I was developing this guide, I have also considered that maybe we can simplify the model by removing the release branch and bump directly from develop to master, reducing the complexity of the model and its implementation.

Feel free to play around with the repo to see how it works or just have a look at the current commits in it.
Maybe we can think on make an interactive session to show how this works in the next developers meeting.

Cheers,

**Comment by marcus-oscarsson** [comment]
:+1: Really nicely done @jordiandreu, bravo :)

**Comment by marcus-oscarsson** [comment]
@jordiandreu, the bumpversion you are using is it this one then?

    https://github.com/c4urself/bump2version

**Comment by marcus-oscarsson** [comment]
Ill merge this as we discussed this on our last meeting and everybody was happy with the work. We might need to give it an update at some point but its in my opinion good as it is. Please let me know if you have some changes to make or make PR :)

**Pull request merged**
