### PR TITLE
Set `sphinx-material` theme for documentation

### PR DESCRIPTION
**Pull request by fabcor-maxiv**

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
Preview: https://mxcubecore--867.org.readthedocs.build/en/867/

Prompted by: https://github.com/mxcube/mxcubeweb/issues/1116

**Comment by marcus-oscarsson** [comment]
It looks quite nice, but there seems to be items missing in the contents right ?

**Comment by marcus-oscarsson** [comment]
thanks, It looks nice but it has the same issue as `furo` with the API contents I believe (not all the text is shown)

**Comment by fabcor-maxiv** [comment]
There has to be a way to improve this. I have some ideas, but have not had the time to try them yet. Well, one or two I tried and it did not improve things.

Maybe there is another theme out there that fits our needs better.

**Comment by marcus-oscarsson** [comment]
I'm sure there is some way as well, lets go with whats easiest for now unless you really want to dig into this.

**Comment by marcus-oscarsson** [comment]
Input on this one, do we keep the current layout or do we try this one, seeing that both are suffering from similar limitations when it comes to the left side menu ?

**Comment by fabcor-maxiv** [comment]
The one we have at least does not truncate the names in left and right columns, and in general I think I prefer the one we currently have.

So if it were only me, for now, I would leave as is (furo).

But I still intend to spend some time fiddling with configuration settings and themes and maybe I find a better compromise.

`furo` (current):

image

`sphinx-material`:

image

**Comment by marcus-oscarsson** [comment]
Ok, We will keep it open for now then, you can close it if you consider it as done

**Comment by marcus-oscarsson** [comment]
Closing this for now, please feel free to re-open if you like

**Pull request closed without merging**
