### PR TITLE
P11 develop bug fixes after upgrade

### PR DESCRIPTION
**Pull request by agruzinov**
Here are a number of changes only to the HO/DESY/... part corresponding mostly to the changes in the AbstractShutter class.

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
OK after a very cursory look (it being all P11-specific)

**Comment by marcus-oscarsson** [comment]
Thanks !

**Comment by marcus-oscarsson** [comment]
Well done @agruzinov

**Comment by agruzinov** [comment]
Thanks for looking into this!

**Pull request merged**
