### PR TITLE
Update documentation pages

### LINKED ISSUE #831: Move wiki content to `/docs`
Now that we have the setup with Sphinx (and ReadTheDocs) automatically building documentation, and now that we have the "documentation camp" in perspective, I want to start working a bit more on content. First things first, I want to move the content of the wiki to the new Sphinx-based setup in `/docs`.

So this is a follow-up to https://github.com/mxcube/mxcubecore/issues/797 and https://github.com/mxcube/mxcubecore/issues/804, and it is related to https://github.com/mxcube/mxcubecore/issues/812.

### PR DESCRIPTION
**Pull request by fabcor-maxiv**
GitHub: closes https://github.com/mxcube/mxcubecore/issues/831

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
@rhfogh

The preview is here: https://mxcubecore--833.org.readthedocs.build/en/833/dev/json-schema-generated-user-interface.html

I made some light edits, heading structure and formatting only. I do not think I did any edits about typos, punctuation, and things like that.

**Comment by fabcor-maxiv** [comment]
The images have been copied into the repository, so that we do not depend on the images from the wiki page.

**Comment by marcus-oscarsson** [comment]
Looks good to me, @rhfogh are you happy with the result ?

**Comment by rhfogh** [comment]
Yes, I am very happy with it.

**Comment by fabcor-maxiv** [comment]
@rhfogh @marcus-oscarsson 

Deprecation notice added to the Wiki:

* https://github.com/mxcube/mxcubecore/wiki/JSON-schema-generated-user-interface

**Pull request merged**
