### PR TITLE
Add sample_environment to the beamline properties.

### PR DESCRIPTION
**Pull request by beteva**
Resolves issue #628.

### CODE REVIEW

**Comment by rhfogh** [comment]
This looks fine - but would it not be better to add the AbstractSampleEnvironment at the same time, so we can see how it will be - and so the type given nin this change matches something existing? I am also curious whether this will contain only the temperature or eventually?) also other attributes.

**Review by IvarsKarpics — APPROVED** [review]

**Comment by marcus-oscarsson** [comment]
I also think its a good idea to draft/discuss what `AbstractSampleEnvironment` would include so that everybody can get an idea of what it is.

**Comment by beteva** [comment]
The idea behind the sample environment is to be able to access directly (and not through diffractometer) any sample environment device.
For now we only have reading of the temperature of the cryo stream. But in a near future, we will need changing this temperature (immediately or by ramping) and I could think of other parameters as pressure. For this I am not quite sure if the simple get_value/set_value mechanism is enough. If we do have only one parameter (e.g. only temperature) we could read it with get_value. Bit a simple set_value needs a prerequisite that it sets the value immediately. Than we may add other custom (not abstract) commands as ramp, start/stop ... Things get more complicated if we have more than one sample environment parameter, but this is not the case for now. For this I thought that AbstractSampleEnvironment is maybe not needed, as we cannot really specify generic methods, other than already available get/set value. if we do go for  AbstractSampleEnvironment methods like get_units/set_units can be useful.

**Comment by marcus-oscarsson** [comment]
I think that it might be better to add the access to the `cryo` and `humidifier` directly onto the beamline object for the time being. Do we really need to encapsulate them in a `AbstractSampleEnvironment`.

Or do you foresee some functionality to over-arches everything in the "sample enviroment" ?

**Comment by beteva** [comment]
I do not think we need AbstractSampleEnvironment. Please see  issue #628.

**Pull request merged**
