### PR TITLE
port CentringMath HWOBJ to work with the yaml config API changes

### PR DESCRIPTION
**Pull request by elmjag**
Don't use [] expression to read config properties.

Renamed attributes `self.cameraAxes` and `self.gonioAxes`, to `self._camera_axes` and `self._gonio_axes`, as they now collide with the 'auto created' properties on the ConfiguredObject superclass.

Use calls to `self.get_property()` when populating these attributes.

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
This really looks very neat. A question: This will clearly work for XML-configured cases, and convert them to a sensible data structure. Is it supposed to also work for yml-configured cases (I cannot quite see how) or is this an intermediate step that will require recoding once you switch to yaml configuration files?

**Comment by elmjag** [comment]
> Is it supposed to also work for yml-configured cases (I cannot quite see how) or is this an intermediate step that will require recoding once you switch to yaml configuration files?

Yes, it works with YAML files as well. I have tested both with XML and YAML configuration files.

It uses `self.get_property()` calls to read gonio and camera axis configurations. On yaml branch `self.get_property()` returns identical data structures for both XML and YAML config files.

**Comment by rhfogh** [comment]
OK, I had missed a few tricks reading it (including the fact that some functions were defined only inside other functions). This is even neater than I had noticed.
To help  me understand it further, could you send me the equivalent yaml configuration file? Also, is it the plan that eventually the data should be defined straightforwardly in a yaml config file and end up inside the CentringMath.config attribute? Meanwhile, how could one access this from outside the object, except by going through the internal (underline-started) attributes?

**Comment by elmjag** [comment]
> To help me understand it further, could you send me the equivalent yaml configuration file? 

This is the XML file I used for testing.

```
<device class="CentringMath">
  <gonioAxes>
     <axis>
        <motorname>phiy</motorname>
        <direction>[0, -1, 0]</direction>
	<type>translation</type>
	<motorHO>udiff_phiy</motorHO>
     </axis>

     <axis>
        <motorname>phiz</motorname>
        <direction>[1, 0, 0]</direction>
        <type>translation</type>
        <motorHO>udiff_phiz</motorHO>
     </axis>

     <axis>
        <motorname>phi</motorname>
        <direction>[0, -1, 0]</direction>
        <type>rotation</type>
        <motorHO>udiff_omega</motorHO>
     </axis>

     <axis>
        <motorname>sampx</motorname>
        <direction>[0,0,1]</direction>
        <type>translation</type>
        <motorHO>udiff_sampx</motorHO>
     </axis>

     <axis>
        <motorname>sampy</motorname>
        <direction>[-1,0,0]</direction>
        <type>translation</type>
        <motorHO>udiff_sampy</motorHO>
     </axis>
  </gonioAxes>
   
  <cameraAxes>
     <axis>
        <axisname>X</axisname>
        <direction>[1, 0, 0]</direction>
     </axis>
     <axis>
        <axisname>Y</axisname>
        <direction>[0, 1, 0]</direction>
     </axis>
  </cameraAxes>
</device>
```

This is the YAML I used in testing. (Generated by the MXCuBE-web migration mode).

```
class: CentringMath.CentringMath
configuration:
  cameraAxes:
    axis:
      - axisname: X
        direction: '[1, 0, 0]'
      - axisname: Y
        direction: '[0, 1, 0]'
  gonioAxes:
    axis:
      - direction: '[0, -1, 0]'
        motorHO: udiff_phiy
        motorname: phiy
        type: translation
      - direction: '[1, 0, 0]'
        motorHO: udiff_phiz
        motorname: phiz
        type: translation
      - direction: '[0, -1, 0]'
        motorHO: udiff_omega
        motorname: phi
        type: rotation
      - direction: '[0,0,1]'
        motorHO: udiff_sampx
        motorname: sampx
        type: translation
      - direction: '[-1,0,0]'
        motorHO: udiff_sampy
        motorname: sampy
        type: translation

```

> Also, is it the plan that eventually the data should be defined straightforwardly in a yaml config file and end up inside the CentringMath.config attribute? Meanwhile, how could one access this from outside the object, except by going through the internal (underline-started) attributes?

I'm not aware of any plans regarding this. But I would suggest to document and implement a dedicated `CenteringMath` hardware object API. Say there should be `get_gonio_axes()` and `get_camera_axes()` methods, that return the axes in some specified format.

**Comment by rhfogh** [comment]
@elmjag

Thanks, I do understand now. 

For the medium term I would propose 

1) to get rid of 'axis', so that the yaml file read
  gonioAxes:
      - direction: '[0, -1, 0]'
        motorHO: udiff_phiy
        motorname: phiy
        type: translation
      - direction: '[1, 0, 0]'
        motorHO: udiff_phiz
        motorname: phiz
        type: translation

etc.
Outside of xml there is no need for the additional nesting level defined by 'axis'.

2) to put gonioAxes and cameraAxes inside .config same as the other properties, and access them directly without the need for special getter functions. It would be simpler that way.

That is in the medium term, though. In the short term your changes makes it possible to work with a mixture of XML and YAML - and I very much approve.

**Review by rhfogh — APPROVED** [review]
We might want further simplifications later, but this excellent for now.

**Pull request merged**
