### PR TITLE
Fix copyright in the `py_file_header.txt` template

### PR DESCRIPTION
**Pull request by fabcor-maxiv**

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
I looked at this document for reference: <https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects>

**Comment by beteva** [comment]
@fabcor-maxiv thanks for the initiative.
@rhfogh, we were discussing about removing the year(s) in the Copyright statement.  Could you, please, check if this is OK with GPhL, as you are a non-synchrotron member of the collaboration.

**Comment by rhfogh** [comment]
@beteva I am checking.

**Comment by marcus-oscarsson** [comment]
Fine for me, @rhfogh can you merge when you checked on your side ?

**Comment by rhfogh** [comment]
I have asked, but got no answer. I shall ask again. Sorry.

**Comment by marcus-oscarsson** [comment]
@rhfogh: I let you merge this once you have confirmation that its ok

**Review by rhfogh — APPROVED** [review]

**Comment by rhfogh** [comment]
I tried 'Rebase and merge' but got a failure. I have approved the PR, but maybe the original author will find it easier to merge?

My apologies for reacting so late. I had mailed a question to my colleagues twice but got no answer, so this time I asked in person.

**Comment by marcus-oscarsson** [comment]
No probem ! thanks

**Pull request merged**
