### PR TITLE
refactoring get_objects_by_role() in HardwareObjectNode class

### PR DESCRIPTION
**Pull request by HilbertCorsair**
This is the refactoring that was discused in my previous PR. This new PR should eliminate the coplications of the previous atempt.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Thanks, its a clear improvement very nice :+1: 

There seems to be some linting errors. Apart from that it would be really nice with a test case for this, especially since its a very frequently used piece of code and also because it might get changed when we start working on the xml to yml work.

**Comment by fabcor-maxiv** [comment]
Some of the linting issues are unrelated to this pull request, so I fixed them here: https://github.com/mxcube/mxcubecore/pull/858

**Review by rhfogh — APPROVED** [review]
Excellent! Thanks for taking the trouble

**Comment by marcus-oscarsson** [comment]
@rhfogh I think there were still some linting not passing, no problem of fixing them in a follow up PR though.

**Comment by rhfogh** [comment]
Sorry, I guess I jumped the gun there

**Comment by marcus-oscarsson** [comment]
Oh wow, working late :). No problem, I think it happened a few times already and it should be easy enough to fix :) What I think Ill do is to enable the option that blocks merging if the pipeline is failing. However it means that we need to disable the test coverage step for now.

I'm on vacation until Monday, so It has to wait for next week.

**Comment by rhfogh** [comment]
If we start insisting on the pipelines succeeding, then I guess someone would have to help me with mine - it seems to fail every time for my pushes and has never worked as far as I know. But lots of time to look at that later.

**Pull request merged**
