### PR TITLE
yaml configs: a couple of fixes

### PR DESCRIPTION
**Pull request by elmjag**
I had to make these two changes to be able to run mxcube-web, wiith mixed XML and YAML config files for HWOs.

It possible it overlaps slightly with https://github.com/mxcube/mxcubecore/pull/936. However, as we decided to post-prone the Pydantic changes for later, I'm putting this here.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Thanks !

**Comment by marcus-oscarsson** [comment]
The pre-commit is failing for some reason, it does not seem to be files that you changed. 

I let you decide exactly how to do, either you merge this as it is and we follow up with a lint fix later or you include in this PR

**Comment by elmjag** [comment]
The the pre-commit was failing on the original xml_yaml_conversion branch. I was not sure to do about that. I have added commits to fix reported errors.

Now, I see that the tests are failing, I'll take a look at what is going on.

**Comment by marcus-oscarsson** [comment]
Its ok for the tests I think, its because the syntax in the yml files changed from _class to class and so on

**Comment by marcus-oscarsson** [comment]
Ill merge this and we will take care of the tests later

**Pull request merged**
