### PR TITLE
Bug fixes to make qt mockup work

### PR DESCRIPTION
**Pull request by MartinSavko**

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
All fine!

**Comment by MartinSavko** [comment]
Not sure about how to read the coverage report problem, is it just something in the configuration of the workflow itself that should be fixed ?

**Comment by rhfogh** [comment]
@MartinSavko I do not know either. Maybe @marcus-oscarsson  or @oldfielj-ansto  have something to say?

**Comment by marcus-oscarsson** [comment]
We are still looking into why that workflow/action is failing.

**Comment by marcus-oscarsson** [comment]
PR looks good, thanks !

**Pull request merged**
