### PR TITLE
Add hierarchy scheme.

### PR DESCRIPTION
**Pull request by beteva**

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
It is very good to have this.

I can pick a couple of nits, though.

The link from Beamline to HardwareObject is not a subclass relationship like the others but a containment link, Maybe a different type of arrow (subclass is generally colored, open-headed arrows).

Typos (updatr_state, AbstracResolution)

I am not quit e clear what it means that valueChanged is written in both AbstractActuator and its subclass AbstractMotor

Would it help to have this a a pptx file (so others can edit if there are minor changes) or are you happy to have it so only can edit it?

I did NOT choose to 'request changes', so you are welcome to merge as it stands.

**Comment by beteva** [comment]
> I am not quite clear what it means that valueChanged is written in both AbstractActuator and its subclass AbstractMotor

The method, which sends the signal (update_value) is overloaded in AbstractMotor. That's why it is the AbstractMotor and not AbstractActuator that sends the signal in this case.

**Comment by rhfogh** [comment]
@beteva Makes sense..

**Comment by marcus-oscarsson** [comment]
I also think this is a great start ! It would be really nice though if we can use some UML modeling tool, maybe a web based one so that its easy to collaborate and share the schema. Maybe someone already knows a good tool for this, the best thing would be one that can parse python code and generate (at least to get started).

**Pull request merged**
