### PR TITLE
[WIP] P11devel branch

### PR DESCRIPTION
**Pull request by agruzinov**
Here are the cumulative request for the changes done at DESY (P11 beamline) together with Bixente and Jan.

### CODE REVIEW

**Comment by beteva** [comment]
Dear @agruzinov, thank you for the effort putting the DESY P11 code. 
Before getting into implementation details, could you, please, do some cleanup and resolve the conflicts. There are some irrelevant files (*.py-new, *.py-saved,  ...) and directories.
May I suggest as well to check the syntax and the python3 compatibility by using  black --safe and pylint or similar

**Review by rhfogh — CHANGES_REQUESTED** [review]
The standard approach has been that before you make a PR you should (ideally) rebase your branch on the tip of the branch you want to merge it to, or (failing that) merge it locally. Anyway, the PR should contain only changes relative to the current tip, not to an earlier state. Maybe we should discuss this at SOLEIL

**Comment by marcus-oscarsson** [comment]
@rhfogh Good idea, we could have a look if we get some off time during the meeting

**Comment by marcus-oscarsson** [comment]
We will try to have a closer look at this as we said during the meeting, Ill mark it as WIP for the time being :)

**Comment by marcus-oscarsson** [comment]
Closed on request made by @agruzinov

**Pull request closed without merging**
