### PR TITLE
Update pre-commit hooks

### PR DESCRIPTION
**Pull request by fabcor-maxiv**

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Its a bit strange that we need to do all those linting updates, but I guess some configuration must have changed since the first time we ran it.

**Comment by marcus-oscarsson** [comment]
Looks good to me :), thanks !

**Comment by fabcor-maxiv** [comment]
> Its a bit strange that we need to do all those linting updates, but I guess some configuration must have changed since the first time we ran it.

I think that in this pull request, the changes are mostly due to black. Black updates its style every year. And we were using the 2022 style. I quite like the style improvement.

Looks like most of the changes are something like the following, which I believe is indeed much better:

```diff
-        self.energy_scan_parameters[
-            "transmissionFactor"
-        ] = self.transmission.get_value()
+        self.energy_scan_parameters["transmissionFactor"] = (
+            self.transmission.get_value()
+        )
```

**Comment by marcus-oscarsson** [comment]
Yes I find it nicer too

**Pull request merged**
