### PR TITLE
P11 beamtime metadata update

### PR DESCRIPTION
**Pull request by agruzinov**
Update of P11 beamtime metadata managment. Branch on top of p11_live view (PR#937).

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hey @agruzinov there seems to be some sort of conflict, could you have a look ?

**Comment by agruzinov** [comment]
Hey @marcus-oscarsson, I've rebased it. It should be ok now.

**Comment by beteva** [comment]
Looks fine. I was just wondering if you should not set as properties all the hard coded directories (just in case your infrastructure changes). This is your business, though.

**Comment by marcus-oscarsson** [comment]
Thanks @agruzinov

**Comment by agruzinov** [comment]
Thanks to everyone!

**Pull request merged**
