### PR TITLE
Removed name override

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
- Overriding name method gives unexpected names for exporter motors

### CODE REVIEW

**Comment by rhfogh** [comment]
Looks fine in itself. But 1) might it not be worth it to remove that method also from BlissMotor? 
2) (much more controversial) might this be the right time to refactor, renaming the name() method to get_name in the superclass? Of course that is likely rather more demanding.

**Review by rhfogh — APPROVED** [review]
Subject to previous comment

**Comment by marcus-oscarsson** [comment]
Thanks, you are right there should not be any name override for BlisMotor either.

**Comment by marcus-oscarsson** [comment]
For changing from name() to get_name() or maybe even just to the property name ? would be a good idea.  Not part of this PR but we can make another one.

**Comment by rhfogh** [comment]
@marcus-oscarsson I agree - and I still approve of the PR.

**Comment by marcus-oscarsson** [comment]
Created #665

**Pull request merged**
